
# Project configuration specifies the environment setups, resources paths and security,
# which mostly are from engineering aspects. Separating this configuration from the models' hyperparameters
# enables us to automatically search for the best hyperparameters using other ML libraries.

default: &DEFAULT
  input_dir: /home/clear/fbartocc/working_data/test_MNIST
  output_dir: /home/clear/fbartocc/output_data/test_MNIST
  # log_format: '%(asctime)s:%(filename)s:%(funcName)s:[%(levelname)s] %(message)s'
  # split_ratio: 0.9  # training/validation ratio

fashion:
  <<: *DEFAULT
  input_dir: /home/clear/fbartocc/working_data/test_MNIST_fashion
  output_dir: /home/clear/fbartocc/output_data/test_MNIST_fashion